[project]
name = "anchy-english"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask-sqlalchemy==3.1.1",
    "flask==2.3.3",
    "granian>=1.6.3",
    "psycopg2-binary==2.9.9",
]
